# Generated by Django 4.1.3 on 2022-11-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blurchatuser',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='blurchatuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blurchatuser',
            name='send_to_email',
        ),
    ]
