# Generated by Django 4.1.3 on 2022-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
        ('authapp', '0002_rename_password_hash_blurchatuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurchatuser',
            name='chat',
            field=models.ManyToManyField(to='chatapp.chat'),
        ),
    ]
