# Generated by Django 4.1.3 on 2022-11-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_rename_password_hash_blurchatuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.chat')),
                ('from_user', models.ForeignKey(on_delete=models.SET('DELETED'), to='authapp.blurchatuser')),
            ],
        ),
    ]
