# Generated by Django 4.1.3 on 2022-11-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(max_length=16),
        ),
    ]
