# Generated by Django 4.1.3 on 2022-11-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_is_read_alter_message_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time',
            new_name='date_client',
        ),
        migrations.AddField(
            model_name='message',
            name='time_client',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
