# Generated by Django 4.1.3 on 2022-11-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_time_message_date_client_message_time_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
